name: Keep App Awake Bus Stop Profiling
on:
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -I https://bus-stop-survey-dpl6qeby3stuvpiexjhovk.streamlit.app/
