[google]
type = "service_account"
project_id = "valid-verbena-463105-h1"
private_key_id = "5fcb8e6a57d3d8ff11b102c808d4d8cc90bb693c"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC/x8ZxknP0v3Z+
GGsFQHSRjMu0aLv6o5kOGG+dhuwg6RypAObxdJZrxut4uAF6sRO9OOGJZ3FKwzq4
kniCtQkePJJswZ7kses9e3qSH1ek+lfiIOuTfmobdI/db65zf3Y8viBTOaBtOgd6
Z1b6hsoTaJoZqS0XjZURPuNqHez4YQlVgfFRnCfIv2mSYO2rzW7HmzOZVj2G5cn/
vzANQm+Azz1kSr6GM5H1e586yxYft4iYtOiaFNK0+s4VhcCjER0g5kdXJKUDtXT0
vJ3HhVhJgkuAZgrMhWxhE/cs+IlS8CdF1JPysfszkvRlngYhvpSUljeYa2lWVYAV
fVGeYAMrAgMBAAECggEAAUEP+kKZGknmU7vGOcsGxjSoKoiQaA8ttOCNHLVj6RUG
x7HV6mVQkXigKyWXdvb/m216OBpQiNorJjLZu+awLY6K2WS0Rl2XvFUYKyBXTiDK
gHU/0KiHwd4/LEiP/Kxfam7gQ9c5vALi6vP7sTYVmuYgrfAUljrdQjxF3lS544kK
kESCXYNP8i3e4NLl1slkYm44LSh45IJ1qjeatRt/y7/DXRmqH18E3Fch73qopHvE
CSF13MJ2hW7Bmr1mY638m0zFjKsSCpVyzxueneUp69OT72/L+7zRTqDFrx8lTU0M
Xv2wZKimJbCoQYIDcx12qrUkpLOZnvvGe4MEGmmIAQKBgQD17+ZNEGg7oXJx5+Tf
FKofbpRA/Y8alW4YauK7ZRks9TvotfJijCg5ExhwVXDo3zspphLblnyuY0OCwqxI
IIyFz6aOwnjPcT9IM4iCUmJIonvlMkammy6ayDEavml7kkiSFr8fF2hlNISM0sWc
/KC105hJBADlUlkISVnZt+ErKwKBgQDHoJqPCVrPCIE5ARk8BRwu5lCwV9hnlhgN
yTFkWt0ipK/+nfATxmxC8Gqj53hgWG73r1pjbCuPbvlrYNL9gnjzlm6Cc5dyq8tM
I+A6hXq22Tl1JVececgdqCFVasEGAd0w7g8xrVoj3FZXqG1M7zHOvS/fmJtyW0r5
8AO6zrCIAQKBgBfNk0WsK9pxoskBf7ZToq+OHU04/Uu+YLx+Q9mNTGV8isLYMVB2
bkIv5fKhYl83k9tRFowoQYMDWnpiaxhEBjXBRkaU7ept9IkBa9npLVgIWeNx/UKM
zHLwo0gKW9046EszZmYU9uassZOLptKt5MQUaa3PdGK9mJ5jsw2ObX2nAoGBAJQ+
dAicjc8JJc1LP44OzWsWpf0OfyoNkDdMnV1FDMrZOcj/SHWm+GaNWuP01LPXeDB/
C8ShY4fUhWx0LrsL1P4vTEmbxW/mm8YjLjTHQuXeUojn/jO5TB6Z6IciC82GPNhF
MQtXDIVs7sGR1fk39+jrHU4Saf12RittTZfAPeABAoGAdvBCuFnlRPUVa4sEwbKt
NdYlx5B8chmF5U+yzAGHkG4njv+nKbWOccXv8/iRmru5jxDL2fCb9J/7ADapTAbB
5ORG5U35DZtUi1r/TpoUPHJZJh5/6ifh9ZyBdJ9YtTJ1PJwlLSjsBt1hnLioPd7Q
4S3JDBU/LNFylI9foJcQs5s=
-----END PRIVATE KEY-----
"""
client_email = "surveybusstop-sa@valid-verbena-463105-h1.iam.gserviceaccount.com"
client_id = "117867489989944240635"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/surveybusstop-sa%40valid-verbena-463105-h1.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
