gdrive_service_account = """
{
  "type": "service_account",
  "project_id": "...",
  "private_key_id": "...",
  "private_key": "-----BEGIN PRIVATE KEY-----\\n...",
  "client_email": "...@....gserviceaccount.com",
  ...
}
"""
gdrive_folder_id = "your_google_drive_folder_id_here"
