gdrive_service_account_type = "service_account"
gdrive_service_account_project_id = "valid-verbena-463105-h1"
gdrive_service_account_private_key_id = "1d3dffadbbfbf0e25e3df7f3ee64d1d72cbb56a4"
gdrive_service_account_private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDSIlj24vc5hAix
...
-----END PRIVATE KEY-----
"""
gdrive_service_account_client_email = "surveybusstop-sa@valid-verbena-463105-h1.iam.gserviceaccount.com"
gdrive_service_account_client_id = "117867489989944240635"
gdrive_service_account_auth_uri = "https://accounts.google.com/o/oauth2/auth"
gdrive_service_account_token_uri = "https://oauth2.googleapis.com/token"
gdrive_service_account_auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
gdrive_service_account_client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/surveybusstop-sa%40valid-verbena-463105-h1.iam.gserviceaccount.com"
gdrive_service_account_universe_domain = "googleapis.com"

gdrive_folder_id = "1AGobH9QwfAQYEL0nz3z_VB3cW7UeHaJI"
