github_token = "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"
github_repo = "https://github.com/imran1991899/bus-stop-survey"  # your repo name
data_branch = "data"  # branch where you save files
