github_token = "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"
github_repo = "imran1991899/bus-stop-survey"  # ✅ DO NOT include 'github.com'
data_branch = "uploads"  # ✅ DO NOT include trailing slash
